import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container } from "../components/ui";
import Nav from "../components/ui/Nav";
import { ThemeProvider } from "next-themes"
import SocialLinks from "../components/ui/SocialLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex min-h-screen flex-col bg-zinc-50 dark:bg-black">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <header className="border-b border-zinc-100 bg-zinc-200 backdrop-blur dark:border-zinc-800 dark:bg-zinc-800/60">
          <Container>
            <div className="py-4">
              <Nav />
            </div>
          </Container>
        </header>

        <main className="flex-1 py-10">{
          <Container>{children}</Container>
        }</main>

        <footer className="border-t border-zinc-100 bg-zinc-200 py-6 dark:border-zinc-800 dark:bg-zinc-800/60">
          <Container>
            <div className="text-sm text-zinc-600 dark:text-white">© {new Date().getFullYear()} Brody Mouw</div>
          </Container>
          <Container>
            <SocialLinks/>
          </Container>          
        </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
